import Link from 'next/link';
import { Inter } from 'next/font/google';
import Image from 'next/image';
import HorizontalLine from '../components/HorizontalLine';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function RootLayout({ children }) {
  return (
    <div><div className="top-left-image">
    <Image
      src="../assets/shared/logo.svg"
      width={30}
      height={30}
      alt="Picture of the author"
    />
  </div>
  <HorizontalLine />
        <nav>
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/About">About</Link>
            </li>
            {/* Add links to other pages here */}
          </ul>
        </nav>
        {children}
      </div>
  );
}

export default RootLayout;
